version: "3.9"
services:
  django_web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static:/static
    env_file:
      - ./.env
    command: >
      sh -c "chmod u=rwx,g=rwx,o=rwx /app/script.sh &&
      /app/script.sh"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_web
volumes:
  static:
  postgres-db:
